spring.application.name=GeniAi

spring.ai.openai.base-url=https://integrate.api.nvidia.com/v1
spring.ai.openai.api-key=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
spring.ai.openai.chat.model=nvidia/nemotron-3.5-lightning-30b-a3b

weather.api.key=be58a427215e47199a490151261509